version: 0.2
phases:
   install:
     runtime-versions:
         php: 7.3
         nodejs: 12.x
     commands:
         - apt-get update
         - apt-get install -y libpq-dev libzip-dev
         - apt-get install -y php7.3-{bcmath,bz2,intl,gd,mbstring,mysql,zip,common}
         - curl -sS <https://getcomposer.org/installer> | php -- --install-dir=/usr/local/bin --filename=composer
   pre_build:
     commands:
         - cp .env.example .env
         - composer install
         - npm install
   build:
     commands:
         - npm run production
         - php artisan migrate --force
         - php artisan db:seed
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes