version: 0.2
phases:
   install:
     runtime-versions:
         php: 7.3
         nodejs: 12.x
     commands:
   pre_build:
     commands:
         - cp .env.example .env
         - composer install
         - npm install
   build:
     commands:
         - npm run production
         # - php artisan migrate --force
         # - php artisan db:seed
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes
